import { supabase } from '../lib/supabase.ts'
import type { Anime } from '../types/anime.ts'
import { cleanText } from '../lib/text.ts'
type AnimeRow = { id: string; anilist_id: number; mal_id: number | null; title: string; title_native: string | null; title_romaji: string | null; title_english: string | null; synonyms: string[] | null; description: string | null; cover_image: string | null; banner_image: string | null; episodes: number | null; format: string | null; season_year: number | null; average_score: number | null; popularity: number | null; genres: string[] | null; status: string | null; season: string | null }
export function mapAnime(item: AnimeRow): Anime { return { id: item.id, anilistId: item.anilist_id, malId: item.mal_id, title: cleanText(item.title), nativeTitle: cleanText(item.title_native) || null, romajiTitle: cleanText(item.title_romaji) || null, englishTitle: cleanText(item.title_english) || null, synonyms: (item.synonyms ?? []).map(cleanText).filter(Boolean), type: item.format, episodes: item.episodes, score: item.average_score ? item.average_score / 10 : null, synopsis: cleanText(item.description) || null, imageUrl: item.cover_image ?? '', year: item.season_year, bannerImage: item.banner_image, status: item.status, season: item.season, popularity: item.popularity, genres: item.genres ?? [] } }
function ensureClient() { if (!supabase) throw new Error('Anime service is not configured'); return supabase }
export async function getTopAnime(limit = 12): Promise<Anime[]> { const { data, error } = await ensureClient().from('anime').select('*').order('popularity', { ascending: false, nullsFirst: false }).limit(limit); if (error) throw error; return (data as AnimeRow[]).map(mapAnime) }
export async function getAnimeById(id: string): Promise<Anime> { const { data, error } = await ensureClient().from('anime').select('*').eq('id', id).maybeSingle(); if (error) throw error; if (!data) throw new Error('Anime was not found'); return mapAnime(data as AnimeRow) }
export async function searchAnime(query: string, limit = 12): Promise<Anime[]> { const normalized = query.normalize('NFKC').replace(/[^\p{L}\p{N}]+/gu, ' ').replace(/\s+/g, ' ').trim(); if (!normalized) return []; const { data, error } = await ensureClient().functions.invoke('search-anime', { body: { query: normalized, limit } }); if (error) throw error; if (data?.error) throw new Error(data.error); return ((data?.results ?? []) as AnimeRow[]).map(mapAnime) }
const starterQueries = ['Naruto', 'Bleach', 'One Piece', 'Demon Slayer: Kimetsu no Yaiba', 'Attack on Titan', 'My Hero Academia'] as const
function titleValues(anime: Anime) { return [anime.title, anime.englishTitle, anime.romajiTitle, anime.nativeTitle, ...anime.synonyms].filter((value): value is string => Boolean(value)).map((value) => value.toLowerCase()) }
export async function getStarterAnime(): Promise<Anime[]> { const groups = await Promise.all(starterQueries.map((query) => searchAnime(query, 12))); return groups.map((items, index) => { const query = starterQueries[index].toLowerCase(); const aliases = query.startsWith('demon slayer') ? ['demon slayer', 'kimetsu no yaiba'] : [query]; return items.find((anime) => titleValues(anime).some((value) => aliases.some((alias) => value === alias || value.startsWith(`${alias}:`)))) ?? items.find((anime) => titleValues(anime).some((value) => aliases.some((alias) => value.includes(alias)))) }).filter((anime): anime is Anime => Boolean(anime)) }
export async function getAiringAnime(limit = 6): Promise<Anime[]> { const { data, error } = await ensureClient().from('anime').select('*').in('status', ['RELEASING', 'NOT_YET_RELEASED']).order('popularity', { ascending: false, nullsFirst: false }).limit(limit); if (error) throw error; return (data as AnimeRow[]).map(mapAnime) }

export async function getAnimeByAnilistId(anilistId: number): Promise<Anime | null> {
	const { data, error } = await ensureClient().from('anime').select('*').eq('anilist_id', anilistId).maybeSingle()
	if (error) throw error
	if (!data) return null
	return mapAnime(data as AnimeRow)
}
