import type { AnimeDNAShareCardData } from './dnaShareModel.ts'

export const DNA_CARD_WIDTH = 1080
export const DNA_CARD_HEIGHT = 1350
function wrap(ctx: CanvasRenderingContext2D, text: string, x: number, y: number, max: number, line: number, maxLines = 3) { let current = ''; let lines = 0; for (const word of text.split(' ')) { const next = current ? `${current} ${word}` : word; if (ctx.measureText(next).width > max && current) { ctx.fillText(current, x, y); lines += 1; if (lines >= maxLines) return; current = word; y += line } else current = next } if (current && lines < maxLines) ctx.fillText(current, x, y) }
function loadImage(url: string): Promise<HTMLImageElement> { return new Promise((resolve, reject) => { const image = new Image(); image.crossOrigin = 'anonymous'; image.onload = () => image.naturalWidth > 0 ? resolve(image) : reject(new Error('Artwork has no pixels.')); image.onerror = () => reject(new Error('Artwork could not be loaded.')); image.src = url }) }
function rounded(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number) { ctx.beginPath(); ctx.roundRect(x, y, w, h, r); ctx.closePath() }
export async function renderDNAImage(data: AnimeDNAShareCardData): Promise<Blob> {
  const canvas = document.createElement('canvas'); canvas.width = DNA_CARD_WIDTH; canvas.height = DNA_CARD_HEIGHT; const ctx = canvas.getContext('2d'); if (!ctx) throw new Error('Image rendering is not supported in this browser.')
  const accent = '#b8c7ff'; const bg = '#151a38'; ctx.fillStyle = '#06070a'; ctx.fillRect(0, 0, DNA_CARD_WIDTH, DNA_CARD_HEIGHT); ctx.fillStyle = bg; rounded(ctx, 28, 28, 1024, 1294, 24); ctx.fill(); ctx.strokeStyle = accent; ctx.lineWidth = 5; ctx.stroke(); ctx.strokeStyle = '#4a4f5b'; ctx.lineWidth = 2; rounded(ctx, 45, 45, 990, 1260, 16); ctx.stroke()
  ctx.fillStyle = accent; ctx.font = '700 34px Arial'; ctx.textAlign = 'center'; ctx.fillText('SAIKO', 540, 92); ctx.fillStyle = '#a7adb8'; ctx.font = '600 20px Arial'; ctx.fillText('ANIME DNA CARD', 540, 124)
  const artX = 78; const artY = 155; const artW = 924; const artH = 515; ctx.fillStyle = '#090b10'; ctx.fillRect(artX, artY, artW, artH); ctx.strokeStyle = accent; ctx.lineWidth = 3; ctx.strokeRect(artX, artY, artW, artH); ctx.strokeStyle = '#555b67'; ctx.lineWidth = 1; ctx.strokeRect(artX + 13, artY + 13, artW - 26, artH - 26)
  let artwork: HTMLImageElement | null = null; if (data.featuredCharacter?.imageUrl) { try { artwork = await loadImage(data.featuredCharacter.imageUrl) } catch { artwork = null } }
  if (!artwork) for (const anime of data.dna.favoriteAnime) { for (const url of [anime.imageUrl, anime.bannerImage ?? '']) { if (!url) continue; try { artwork = await loadImage(url); break } catch { /* try the next trusted Core 3 asset */ } } if (artwork) break }
  if (artwork) { const ratio = Math.min((artW - 30) / artwork.naturalWidth, (artH - 30) / artwork.naturalHeight); const w = artwork.naturalWidth * ratio; const h = artwork.naturalHeight * ratio; ctx.drawImage(artwork, artX + (artW - w) / 2, artY + (artH - h) / 2, w, h) } else { const glow = ctx.createRadialGradient(540, 410, 20, 540, 410, 400); glow.addColorStop(0, `${accent}55`); glow.addColorStop(1, '#090b1000'); ctx.fillStyle = glow; ctx.fillRect(artX, artY, artW, artH); ctx.fillStyle = accent; ctx.font = '700 30px Arial'; ctx.fillText('SAIKO', 540, 425) }
  ctx.textAlign = 'left'; ctx.fillStyle = '#0b0d12'; ctx.fillRect(artX, 685, artW, 76); ctx.strokeStyle = accent; ctx.strokeRect(artX, 685, artW, 76); ctx.textAlign = 'center'; ctx.fillStyle = '#f4f5f7'; ctx.font = '700 31px Arial'; ctx.fillText((data.featuredCharacter?.name ?? data.dna.favoriteAnime[0]?.title ?? 'YOUR CHARACTER').toUpperCase(), 540, 720); ctx.fillStyle = '#a7adb8'; ctx.font = '18px Arial'; ctx.fillText(`FEATURED FROM ${(data.featuredCharacter?.animeTitle ?? data.dna.favoriteAnime[0]?.title ?? 'YOUR CORE 3').toUpperCase()}`, 540, 748)
  ctx.textAlign = 'left'; ctx.fillStyle = accent; ctx.font = '700 19px Arial'; ctx.fillText('YOUR ANIME DNA', 78, 812); ctx.fillStyle = '#f4f5f7'; ctx.font = '700 34px Arial'; wrap(ctx, data.dna.archetype.name, 78, 858, 900, 36, 2); ctx.fillStyle = '#bac0ca'; ctx.font = '19px Arial'; wrap(ctx, data.dna.description, 78, 918, 900, 25, 2)
  ctx.strokeStyle = '#4a4f5b'; ctx.lineWidth = 1; ctx.beginPath(); ctx.moveTo(78, 980); ctx.lineTo(1002, 980); ctx.stroke(); ctx.fillStyle = accent; ctx.font = '700 17px Arial'; ctx.fillText('DNA TRAITS', 78, 1017); data.dna.traits.slice(0, 3).forEach((trait, index) => { const y = 1054 + index * 32; ctx.fillStyle = '#f4f5f7'; ctx.font = '18px Arial'; ctx.fillText(`${trait.icon}  ${trait.name.toUpperCase()}`, 78, y); ctx.fillStyle = '#454b57'; ctx.fillRect(390, y - 13, 350, 6); ctx.fillStyle = accent; ctx.fillRect(390, y - 13, 350 * trait.score / 100, 6); ctx.fillStyle = accent; ctx.font = '700 18px Arial'; ctx.fillText(`${trait.score}%`, 780, y) })
  ctx.strokeStyle = '#4a4f5b'; ctx.beginPath(); ctx.moveTo(78, 1160); ctx.lineTo(1002, 1160); ctx.stroke(); ctx.fillStyle = accent; ctx.font = '700 16px Arial'; ctx.fillText('YOUR CORE 3', 78, 1192); ctx.fillStyle = '#f4f5f7'; ctx.font = '600 19px Arial'; ctx.fillText(data.dna.favoriteAnime.slice(0, 3).map((anime) => anime.title).join('  •  '), 78, 1222); ctx.fillStyle = '#a7adb8'; ctx.font = '16px Arial'; ctx.fillText(`@${data.username}`, 78, 1262); ctx.textAlign = 'right'; ctx.fillStyle = accent; ctx.font = '700 15px Arial'; ctx.fillText('DISCOVER YOUR ANIME DNA', 1002, 1262)
  return new Promise((resolve, reject) => canvas.toBlob((blob) => blob ? resolve(blob) : reject(new Error('Could not create image.')), 'image/png'))
}
export function dnaShareUrl(username: string) { return `https://saiko-app.pxxl.click/dna/${encodeURIComponent(username)}` }
export function downloadDNAImage(blob: Blob, username: string) { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `saiko-anime-dna-${username.replace(/[^a-z0-9_-]/gi, '-').toLowerCase() || 'profile'}.png`; link.click(); URL.revokeObjectURL(url) }
