// Public snapshot from project ljkwhsnetasrcpsoqtab, verified 2026-09-08.
// Preserve database UUIDs: favorites reference anime.id, not AniList IDs.
export const starterAnime = [
  {
    "id": "9d475ffe-0504-43d5-8626-cd042960c3f2",
    "anilist_id": 20,
    "mal_id": 20,
    "title": "Naruto",
    "title_native": "NARUTO -ナルト-",
    "title_romaji": "NARUTO",
    "title_english": "Naruto",
    "synonyms": [
      "נארוטו",
      "ناروتو",
      "火影忍者",
      "นารูโตะ นินจาจอมคาถา",
      "Наруто"
    ],
    "description": "Naruto Uzumaki, a hyperactive and knuckle-headed ninja, lives in Konohagakure, the Hidden Leaf village. Moments prior to his birth, a huge demon known as the Kyuubi, the Nine-tailed Fox, attacked Konohagakure and wreaked havoc. In order to put an end to the Kyuubi's rampage, the leader of the village, the 4th Hokage, sacrificed his life and sealed the monstrous beast inside the newborn Naruto. Shunned because of the presence of the Kyuubi inside him, Naruto struggles to find his place in the village. He strives to become the Hokage of Konohagakure, and he meets many friends and foes along the way.",
    "cover_image": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx20-dE6UHbFFg1A5.jpg",
    "banner_image": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/20-HHxhPj5JD13a.jpg",
    "episodes": 220,
    "format": "TV",
    "status": "FINISHED",
    "season": "FALL",
    "season_year": 2002,
    "average_score": 80,
    "popularity": 720260,
    "genres": [
      "Action",
      "Adventure",
      "Comedy",
      "Drama",
      "Fantasy",
      "Supernatural"
    ]
  },
  {
    "id": "4ab9fa27-d981-496d-8a9e-5d90aa59586c",
    "anilist_id": 21,
    "mal_id": 21,
    "title": "One Piece",
    "title_native": "ONE PIECE",
    "title_romaji": "ONE PIECE",
    "title_english": "ONE PIECE",
    "synonyms": [
      "ワンピース",
      "海贼王",
      "וואן פיס",
      "ون بيس",
      "วันพีซ",
      "Vua Hải Tặc",
      "All'arrembaggio!",
      "Tutti all'arrembaggio!",
      "Ντρέηκ, το Κυνήγι του Θησαυρού",
      "OP",
      "Ван-Пис"
    ],
    "description": "Gold Roger was known as the Pirate King, the strongest and most infamous being to have sailed the Grand Line. The capture and death of Roger by the World Government brought a change throughout the world. His last words before his death revealed the location of the greatest treasure in the world, One Piece. It was this revelation that brought about the Grand Age of Pirates, men who dreamed of finding One Piece (which promises an unlimited amount of riches and fame), and quite possibly the most coveted of titles for the person who found it, the title of the Pirate King. Enter Monkey D. Luffy, a 17-year-old boy that defies your standard definition of a pirate. Rather than the popular persona of a wicked, hardened, toothless pirate who ransacks villages for fun, Luffy’s reason for being a pirate is one of pure wonder; the thought of an exciting adventure and meeting new and intriguing people, along with finding One Piece, are his reasons of becoming a pirate. Following in the footsteps of his childhood hero, Luffy and his crew travel across the Grand Line, experiencing crazy adventures, unveiling dark mysteries and battling strong enemies, all in order to reach One Piece. *This includes the following special episodes: - Chopperman to the Rescue! Protect the TV Station by the Shore! (Episode 336) - The Strongest Tag-Team! Luffy and Toriko's Hard Struggle! (Episode 492) - Team Formation! Save Chopper (Episode 542) - History's Strongest Collaboration vs. Glutton of the Sea (Episode 590) - 20th Anniversary! Special Romance Dawn (Episode 907)",
    "cover_image": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21-ELSYx3yMPcKM.jpg",
    "banner_image": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21-wf37VakJmZqs.jpg",
    "episodes": null,
    "format": "TV",
    "status": "RELEASING",
    "season": "FALL",
    "season_year": 1999,
    "average_score": 87,
    "popularity": 744383,
    "genres": [
      "Action",
      "Adventure",
      "Comedy",
      "Drama",
      "Fantasy"
    ]
  },
  {
    "id": "1645d3f9-c638-4c36-9793-a6057bba4cf8",
    "anilist_id": 269,
    "mal_id": 269,
    "title": "Bleach",
    "title_native": "BLEACH",
    "title_romaji": "BLEACH",
    "title_english": "Bleach",
    "synonyms": [
      "ブリーチ",
      "'בליץ",
      "เทพมรณะ",
      "بليتش",
      "Блич"
    ],
    "description": "Ichigo Kurosaki is a rather normal high school student apart from the fact he has the ability to see ghosts. This ability never impacted his life in a major way until the day he encounters the Shinigami Kuchiki Rukia, who saves him and his family's lives from a Hollow, a corrupt spirit that devours human souls. Wounded during the fight against the Hollow, Rukia chooses the only option available to defeat the monster and passes her Shinigami powers to Ichigo. Now forced to act as a substitute until Rukia recovers, Ichigo hunts down the Hollows that plague his town.",
    "cover_image": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx269-d2GmRkJbMopq.png",
    "banner_image": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/269-08ar2HJOUAuL.jpg",
    "episodes": 366,
    "format": "TV",
    "status": "FINISHED",
    "season": "FALL",
    "season_year": 2004,
    "average_score": 79,
    "popularity": 514702,
    "genres": [
      "Action",
      "Adventure",
      "Supernatural"
    ]
  },
  {
    "id": "26076f0d-c448-4072-9356-b1d9f0f2f103",
    "anilist_id": 101922,
    "mal_id": 38000,
    "title": "Demon Slayer",
    "title_native": "鬼滅の刃",
    "title_romaji": "Kimetsu no Yaiba",
    "title_english": "Demon Slayer: Kimetsu no Yaiba",
    "synonyms": [
      "KnY",
      "Kimetsu no Yaiba: Kyoudai no Kizuna",
      "Demon Slayer: Kimetsu no Yaiba: Bonds of Siblings",
      "鬼滅の刃-兄妹の絆-",
      "鬼灭之刃",
      "הלהב קוטל השדים",
      "قاتل الشياطين",
      "ดาบพิฆาตอสูร",
      "Miecz zabójcy demonów – Kimetsu no Yaiba",
      " Guardians de la nit: Kimetsu no Yaiba",
      "İblis Keser",
      "ΚΥΝΗΓΟΣ ΔΑΙΜΟΝΩΝ: KIMETSU NO YAIBA",
      "Zabiják démonů",
      "شیطان کش",
      "귀멸의 칼날",
      "Истребитель демонов",
      "Клинок, рассекающий демонов"
    ],
    "description": "It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a “demon slayer” so that he can turn his sister back into a human, and kill the demon that massacred his family.",
    "cover_image": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101922-WBsBl0ClmgYL.jpg",
    "banner_image": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/101922-33MtJGsUSxga.jpg",
    "episodes": 26,
    "format": "TV",
    "status": "FINISHED",
    "season": "SPRING",
    "season_year": 2019,
    "average_score": 83,
    "popularity": 991252,
    "genres": [
      "Action",
      "Adventure",
      "Drama",
      "Fantasy",
      "Supernatural"
    ]
  },
  {
    "id": "33714e35-4eae-42dc-96a2-67be2c19313c",
    "anilist_id": 21459,
    "mal_id": 31964,
    "title": "My Hero Academia",
    "title_native": "僕のヒーローアカデミア",
    "title_romaji": "Boku no Hero Academia",
    "title_english": "My Hero Academia",
    "synonyms": [
      "BNHA",
      "MHA",
      "나의 히어로 아카데미아 1기",
      "나히아 1기",
      "אקדמיית הגיבורים שלי",
      "我的英雄学院",
      "มายฮีโร่ อคาเดเมีย",
      "أكاديميتي للأبطال",
      "Η Δική Μου Ακαδημία Ηρώων",
      "Akademia bohaterów",
      "Моя геройская академия",
      "Hősakadémia",
      "Học Viện Anh Hùng"
    ],
    "description": "What would the world be like if 80 percent of the population manifested extraordinary superpowers called “Quirks” at age four? Heroes and villains would be battling it out everywhere! Becoming a hero would mean learning to use your power, but where would you go to study? U.A. High's Hero Program of course! But what would you do if you were one of the 20 percent who were born Quirkless? Middle school student Izuku Midoriya wants to be a hero more than anything, but he hasn't got an ounce of power in him. With no chance of ever getting into the prestigious U.A. High School for budding heroes, his life is looking more and more like a dead end. Then an encounter with All Might, the greatest hero of them all gives him a chance to change his destiny…",
    "cover_image": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21459-nYh85uj2Fuwr.jpg",
    "banner_image": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/21459-yeVkolGKdGUV.jpg",
    "episodes": 13,
    "format": "TV",
    "status": "FINISHED",
    "season": "SPRING",
    "season_year": 2016,
    "average_score": 77,
    "popularity": 868638,
    "genres": [
      "Action",
      "Adventure",
      "Comedy"
    ]
  },
  {
    "id": "f059758a-b605-4b49-b8ff-f47fd227b396",
    "anilist_id": 16498,
    "mal_id": 16498,
    "title": "Attack on Titan",
    "title_native": "進撃の巨人",
    "title_romaji": "Shingeki no Kyojin",
    "title_english": "Attack on Titan",
    "synonyms": [],
    "description": "Several hundred years ago, humans were nearly exterminated by titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest of titans.<br><br>\r\nFlash forward to the present and the city has not seen a titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a colossal titan that appears out of thin air. As the smaller titans flood the city, the two kids watch in horror as their mother is eaten alive. Eren vows that he will murder every single titan and take revenge for all of mankind.<br><br>\r\n(Source: MangaHelpers)",
    "cover_image": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx16498-buvcRTBx4NSm.jpg",
    "banner_image": "https://s4.anilist.co/file/anilistcdn/media/anime/banner/16498-8jpFCOcDmneX.jpg",
    "episodes": 25,
    "format": null,
    "status": "FINISHED",
    "season": "SPRING",
    "season_year": 2013,
    "average_score": 85,
    "popularity": 1046082,
    "genres": []
  }
]
